export const bankAccounts = [
  {
    id: "acc_1",
    name: "Main Checking",
    institution: "Chase Bank",
    accountNumber: "****1234",
    balance: 3426.78,
    change: -156.23,
    type: "checking"
  },
  {
    id: "acc_2",
    name: "Savings",
    institution: "Wells Fargo",
    accountNumber: "****5678",
    balance: 12589.45,
    change: 32.19,
    type: "savings"
  },
  {
    id: "acc_3",
    name: "Joint Account",
    institution: "Bank of America",
    accountNumber: "****9012",
    balance: 5230.91,
    change: 0,
    type: "checking"
  },
  {
    id: "acc_4",
    name: "Emergency Fund",
    institution: "Ally Bank",
    accountNumber: "****3456",
    balance: 8500.00,
    change: 8.32,
    type: "savings"
  }
];

export const expenses = [
  {
    id: "exp_1",
    title: "Grocery Shopping",
    amount: 156.23,
    date: "2025-04-15",
    category: "Shopping",
    account: "Main Checking",
    accountId: "acc_1",
  },
  {
    id: "exp_2",
    title: "Monthly Rent",
    amount: 1800.00,
    date: "2025-04-01",
    category: "Housing",
    account: "Main Checking",
    accountId: "acc_1",
  },
  {
    id: "exp_3",
    title: "Phone Bill",
    amount: 89.99,
    date: "2025-04-05",
    category: "Utilities",
    account: "Joint Account",
    accountId: "acc_3",
  },
  {
    id: "exp_4",
    title: "Dinner with Friends",
    amount: 78.45,
    date: "2025-04-12",
    category: "Food",
    account: "Main Checking",
    accountId: "acc_1",
  },
  {
    id: "exp_5",
    title: "Gym Membership",
    amount: 55.00,
    date: "2025-04-03",
    category: "Health",
    account: "Main Checking",
    accountId: "acc_1",
  },
  {
    id: "exp_6",
    title: "Car Insurance",
    amount: 145.50,
    date: "2025-04-10",
    category: "Transportation",
    account: "Joint Account",
    accountId: "acc_3",
  },
  {
    id: "exp_7",
    title: "Online Course",
    amount: 199.99,
    date: "2025-04-08",
    category: "Work",
    account: "Savings",
    accountId: "acc_2",
  },
  {
    id: "exp_8",
    title: "Movie Tickets",
    amount: 32.50,
    date: "2025-04-14",
    category: "Entertainment",
    account: "Main Checking",
    accountId: "acc_1",
  },
  {
    id: "exp_8",
    title: "Movie Tickets",
    amount: 32.50,
    date: "2025-04-14",
    category: "Entertainment",
    account: "Main Checking",
    accountId: "acc_1",
  },
  {
    id: "exp_8",
    title: "Movie Tickets",
    amount: 32.50,
    date: "2025-04-14",
    category: "Entertainment",
    account: "Main Checking",
    accountId: "acc_1",
  },
  {
    id: "exp_8",
    title: "Movie Tickets",
    amount: 32.50,
    date: "2025-04-14",
    category: "Entertainment",
    account: "Main Checking",
    accountId: "acc_1",
  },
  {
    id: "exp_8",
    title: "Movie Tickets",
    amount: 32.50,
    date: "2025-04-14",
    category: "Entertainment",
    account: "Main Checking",
    accountId: "acc_1",
  },
  {
    id: "exp_8",
    title: "Movie Tickets",
    amount: 32.50,
    date: "2025-04-14",
    category: "Entertainment",
    account: "Main Checking",
    accountId: "acc_1",
  },
  {
    id: "exp_8",
    title: "Movie Tickets",
    amount: 32.50,
    date: "2025-04-14",
    category: "Entertainment",
    account: "Main Checking",
    accountId: "acc_1",
  },
  {
    id: "exp_8",
    title: "Movie Tickets",
    amount: 32.50,
    date: "2025-04-14",
    category: "Entertainment",
    account: "Main Checking",
    accountId: "acc_1",
  },
  {
    id: "exp_8",
    title: "Movie Tickets",
    amount: 32.50,
    date: "2025-04-14",
    category: "Entertainment",
    account: "Main Checking",
    accountId: "acc_1",
  },
  {
    id: "exp_8",
    title: "Movie Tickets",
    amount: 32.50,
    date: "2025-04-14",
    category: "Entertainment",
    account: "Main Checking",
    accountId: "acc_1",
  },
  {
    id: "exp_8",
    title: "Movie Tickets",
    amount: 32.50,
    date: "2025-04-14",
    category: "Entertainment",
    account: "Main Checking",
    accountId: "acc_1",
  },
  {
    id: "exp_8",
    title: "Movie Tickets",
    amount: 32.50,
    date: "2025-04-14",
    category: "Entertainment",
    account: "Main Checking",
    accountId: "acc_1",
  },
];

export const expenseData = [
  { date: "Apr 01", amount: 1800 },
  { date: "Apr 03", amount: 1855 },
  { date: "Apr 05", amount: 1945 },
  { date: "Apr 08", amount: 2145 },
  { date: "Apr 10", amount: 2290 },
  { date: "Apr 12", amount: 2368 },
  { date: "Apr 14", amount: 2401 },
  { date: "Apr 15", amount: 2557 }
];

export const categoryData = [
  { name: "Housing", value: 1800 },
  { name: "Food", value: 234.68 },
  { name: "Transportation", value: 145.5 },
  { name: "Health", value: 55 },
  { name: "Shopping", value: 156.23 },
  { name: "Entertainment", value: 32.5 },
  { name: "Work", value: 199.99 },
];